### ISSUE TITLE
Estimated code release?

### ISSUE THREAD

**Issue by vishaal27** [linzhiqiu/visual_gpt_score#1]
Hey, thanks for the great paper!
Do you have an estimated timeline in mind for the code release?

**Comment by linzhiqiu** [comment]
It will be next week! We will also attach the most recent SOTA results on SugarCrepe.

**Comment by linzhiqiu** [comment]
Hey Vishaal, I am sorry to update but because the work is currently in submission, we plan to release it once we hear back from the reviewers. In the meantime, if you want some code snippets, please shoot me an email at: zhiqiul@andrew.cmu.edu
